greet_phrase = "Привет 👋, я - бот, который поможет тебе со все возможной обработкой изображений!"
send_me_photo_phrase = "Теперь, отправьте мне фото 📸"
enter_sizes_phrase = "Отлично! Теперь введите новые размеры изображения в формате 100x100"
incorrect_format_of_sizes_phrase = "Не правильный формат!"
creating_image_phrase = "Генерирую изображение..."
changed_image_phrase = "Вот измененное изображение!"
